### ISSUE TITLE
Matrix store and olm account is not loaded.

### ISSUE THREAD

**Issue by Setom29** [hibobmaster/matrix-stt-bot#4]
Hello! I have a problem related to e2ee.
I log in using an access token. I followed the instructions and edited the config.json and compose.yaml. I initially ran the Docker image using sudo docker compose without any problems, but after I tried to add e2ee, I found the following error message:

```Python
matrix-stt-bot  | 2023-12-04 09:34:41,890 - INFO - Bot started!
matrix-stt-bot  | 2023-12-04 09:34:43,052 - INFO - Login via access_token
matrix-stt-bot  | 2023-12-04 09:34:43,052 - INFO - start import_keys process, this may take a while...
matrix-stt-bot  | Traceback (most recent call last):
matrix-stt-bot  |   File "/app/src/bot.py", line 632, in <module>
matrix-stt-bot  |     asyncio.run(main())
matrix-stt-bot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
matrix-stt-bot  |     return runner.run(main)
matrix-stt-bot  |            ^^^^^^^^^^^^^^^^
matrix-stt-bot  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
matrix-stt-bot  |     return self._loop.run_until_complete(task)
matrix-stt-bot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
matrix-stt-bot  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
matrix-stt-bot  |     return future.result()
matrix-stt-bot  |            ^^^^^^^^^^^^^^^
matrix-stt-bot  |   File "/app/src/bot.py", line 613, in main
matrix-stt-bot  |     await bot.import_keys()
matrix-stt-bot  |   File "/app/src/bot.py", line 537, in import_keys
matrix-stt-bot  |     resp = await self.client.import_keys(
matrix-stt-bot  |                  ^^^^^^^^^^^^^^^^^^^^^^^^
matrix-stt-bot  |   File "/usr/local/lib/python3.11/site-packages/nio/client/base_client.py", line 115, in inner
matrix-stt-bot  |     raise LocalProtocolError("Matrix store and olm account is not loaded.")
matrix-stt-bot  | nio.exceptions.LocalProtocolError: Matrix store and olm account is not loaded.
```

**Comment by Setom29** [comment]
Thanks for the quick reply.
I tried to log in with user_id and password, but it was unsuccessful because of the server configuration. There is OIDC authorization and i can't use user_id and password.

**Comment by hibobmaster** [comment]
Create a matrix account from matrix.org or other providers.

**Comment by Setom29** [comment]
I can't create such accounts because I have self-hosted server with disabled federation. Maybe you can suggest what I can change to make e2ee work using access_token?

**Comment by hibobmaster** [comment]
Sorry, i use matrix-nio library to develop bot. It has poorly document and i can't find a way to achive that.

**Comment by Setom29** [comment]
Okay, thank you. I'll continue my search, and I'll let you know if I find the answer.

**Comment by hibobmaster** [comment]
@Setom29 Please use the latest version and follow the instructions below to make `access_token` work in E2EE room.


1. Open a private browser window and visit your element web url, then login to your bot account via OIDC. 
2. Get current `session id` and `access_token` from element web.
3. Close private browser window and open a new one, revisit your element web url and login bot account via OIDC.
4. Send some text in E2EE room from your normal account, if you can read the decrypted content from private browser window(bot account), then export E2EE room keys from element web(bot account). 
5. Edit your config.json (without the <>), then `docker compose up` 
```json
{
    "homeserver": "https://xxxx.xxxxx",
    "user_id": "@xxxxx:xxxx.xxxxx",
    "access_token": "<access_token>",
    "device_id": "<session id>",
    "model_size": "base",
    "room_id": "<some non exist room id>",
    "import_keys_path": "element-keys.txt",
    "import_keys_password": "<E2EE room keys passphrase>"
}
```
![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/b0373725-d935-4e58-8c7e-7d2367843796)
Some errors can be ignored.

Wait some seconds to let the bot do some syncing, then `Ctrl+C` stop the container. 

6. Remove `import_keys_path` and `import_keys_password` options,  and set a correct `room_id` or remove it if you hope the bot to work in the rooms it is in. 

7. Finally, launch the container in detach mode
```sh
docker compose up -d
```

**Comment by alexander-potemkin** [comment]
@hibobmaster , thank you. Session id is the thing that changes over time, as I conclude from it's name, which means that my bot is not sustainable without man's intervention, which makes it looks more like a script, not a bot... 

As I can see in the [docs](https://matrix.org/docs/matrix-concepts/end-to-end-encryption/) it is not, indeed:

> Megolm sessions may not be reused indefinitely. The parameters which define how often a session should be rotated are defined in the m.room.encryption state event of a room.

**Comment by hibobmaster** [comment]
@alexander-potemkin  You can understand in this way. From element web, you can see how many sessions are there. All of them work unless you manually logout it. (Each session_id has a correspond access_token)
![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/4fd84f76-26e6-4141-bc03-096fc722fc04)

The bot is sustainable without man's intervention after you properly set it up.
Can you try https://github.com/hibobmaster/matrix-stt-bot/issues/4#issuecomment-1840398688 ?

**Comment by alexander-potemkin** [comment]
Thank you and I'm sorry to say that it still doesn't work for me... :/
I followed all of steps down to the dot in them, but the only room it works at - it's unencrypted initial room, that is also happened to be specified in the config.

To make sure it's not some room keys issue, I created a new encrypted room, added my bot there, here is what I have on the console:
```
2023-12-07 21:16:18,569 - INFO - Joined !ycxAopEWqQVtJssZhx:mydomain.com
2023-12-07 21:16:18,714 - INFO - Joined !ycxAopEWqQVtJssZhx:mydomain.com
Olm event doesn't contain ciphertext for our key
Received a undecryptable Megolm event from a device with no Olm sessions: @alex:mydomain.com XFNMXWGKIM
Error decrypting megolm event, no session found with session id tzb+slR8NejmneCYjp29CQKGMeqpyg4CJK5MA5gU9QA for room !ycxAopEWqQVtJssZhx:mydomain.com
2023-12-07 21:16:32,243 - decryption_failure - ERROR - Failed to decrypt message: $Jki6KordOd2Int-cgeVWJYilGn7N0rw9ywep2WedlBE from @alex:mydomain.com             in !ycxAopEWqQVtJssZhx:mydomain.com
Please make sure the bot current session is verified
2023-12-07 21:16:32,243 - ERROR - Failed to decrypt message: $Jki6KordOd2Int-cgeVWJYilGn7N0rw9ywep2WedlBE from @alex:mydomain.com             in !ycxAopEWqQVtJssZhx:mydomain.com
Please make sure the bot current session is verified
```

**Comment by alexander-potemkin** [comment]
And yes - bot's session(s) are all verified. Triple checked that from the browser (logged in as a bot) and from 'regular user' browser.

**Comment by alexander-potemkin** [comment]
Thank you very much. I followed all of the steps you provided, but I'm still getting the error:

```
Received a undecryptable Megolm event from a device with no Olm sessions: @alex:mydomain.com XFNMXWGKIM
Error decrypting megolm event, no session found with session id Awrm7TMzGvFPRIqmB1Sx1a1RPW9ENEF9YXdqgYpOArw for room !GnyRxyvAEIRTVnFpJJ:mydomain.com
2023-12-09 12:21:34,712 - decryption_failure - ERROR - Failed to decrypt message: $gTT1hMxBLbmHG3yKD7R-DF28K6yRvA2nqxTM4oPh4vg from @alex:mydomain.com             in !GnyRxyvAEIRTVnFpJJ:mydomain.com
Please make sure the bot current session is verified
2023-12-09 12:21:34,712 - ERROR - Failed to decrypt message: $gTT1hMxBLbmHG3yKD7R-DF28K6yRvA2nqxTM4oPh4vg from @alex:mydomain.com             in !GnyRxyvAEIRTVnFpJJ:mydomain.com
Please make sure the bot current session is verified
```

I did a few times, resetting the keys, device ids, etc and the issue still persist.
Double checked - all my bot sessions are verified.

Is there probably some ways to understand what exactly is missing? What is the session id that is referred in the error message: `Awrm7TMzGvFPRIqmB1Sx1a1RPW9ENEF9YXdqgYpOArw`?

Or any other help! Would be much appreciated!

**Comment by alexander-potemkin** [comment]
I use login & password for Element client and token for the bot. Guess I can’t login with token on Element, unless I’m missing something?

**Comment by hibobmaster** [comment]
I mean matrix-stt-bot. You can use either password or access token in config.json but not both.

If you use password, use a device_id different from element web session list and follow the instructions in readme.

If you use access token, use the instructions above.

Notice that some errors can be ignored, make sure always send a voice to test.

**Comment by alexander-potemkin** [comment]
I use access token, follow instructions and only sending voice messages… 🙁

**Comment by hibobmaster** [comment]
Can you share me your config.json and compose.yaml with redacted info.

**Comment by alexander-potemkin** [comment]
I'm running bot.py directly from IDE, to catch errors / exceptions and follow the logic (with all files created just next to the script in `src` folder).

Please, find information attached: https://gist.github.com/alexander-potemkin/17d9c86778e54372714c88086a96bc18

Please, let me know once you access / download it, so that I can remove it.

**Comment by hibobmaster** [comment]
I get the same error `Olm event doesn't contain ciphertext for our key` which is not occured in my personal server or `matrix.org` server

**Comment by hibobmaster** [comment]
I got it work finally.
![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/3dc4848d-65a5-46d0-a251-1e69537f81a9)

**Comment by alexander-potemkin** [comment]
Oh, wow! Thanks a lot! I shall test it all very thoroughly and get back to you in a little while!

**Comment by alexander-potemkin** [comment]
Unfortunately, that didn't work... =(
I've tried it on another self-hosted server, but same thing.

One thing - sessions keys dump is getting bigger with every new session / chat in a new room and from the description I can see that they gives access to the past messages, not to the future messages. And Element client generates those sessions keys as required, which makes me think that something is wrong about the way bot handles that data.

I understand that nio documentation is almost absent and Matrix protocol is not so easy to dig into, but it feels like bot shall handle device verification and sessions keys on his own, otherwise something get lost somewhere.

btw, doesn't it feels weird, that with session keys old messages can't be decrypted, despite the fact that those keys are created to enable old messages decrypt?

**Comment by hibobmaster** [comment]
As for matrix bot, we don't care old messages. What i see is when the bot join the new rooms without man's intervention, it works at my end.

If you want the bot handle device verification at the moment(emoji verification), you should login via password.

> Unfortunately, that didn't work

Can you try logout your current normal account, then relogin, export its E2EE room keys and let bot import again?

**Comment by alexander-potemkin** [comment]
@hibobmaster , I appreciate your support and prompt responses - that was really of importance for me.

During the digging into the things I found myself rewriting the functionality with simple-matrix-bot-lib and matrix-commander and I made it finally work.

During my journey I was facing similar issues, until I dropped Element client completely and started using matrix-commander to obtain token - then it was back to normal.

Once again - thank you a lot for your product, time and efforts - I borrowed a few things from there and your support was of really great help!
